#!/usr/bin/env bash
# Vérifier si aucun argument et fourni et effectuer 5 pings vers une adresse IP
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi
ping -c 5 "$1"
