#!/usr/bin/env bash
# Configurer hostsfile et ajouter Facebook
if grep -q "127.0.0.1" /etc/hosts; then
    cp /etc/hosts /tmp/hosts.tmp
    sed 's/127.0.0.1/127.0.0.2/g' /tmp/hosts.tmp > /tmp/hosts.new
    cat /tmp/hosts.new > /etc/hosts
fi

if ! grep -q "8.8.8.8 facebook.com" /etc/hosts; then
    echo "8.8.8.8 facebook.com" >> /etc/hosts
fi
