#!/usr/bin/env bash
# Modifie l'adresse IP du domicile en redémarrant l'interface réseau.
[ "$EUID" -ne 0 ] && echo "Please run as root" && exit 1
echo "127.0.0.2 localhost" > /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
